version: '3.2'
services:
  simple-auth:
    image: thecalcaholic/simple-auth
    volumes:
      - "/etc/rtmp-hls-server/auth_config:/etc/auth_config"
    restart: unless-stopped
  rtmp-hls:
    image: alqutami/rtmp-hls:latest-alpine
    ports:
      - "80:80"
      - "443:443"
      - "1935:1935"
    depends_on:
      - simple-auth
    restart: unless-stopped
    volumes:
      - type: volume
        source: letsencrypt
        target: /etc/letsencrypt
        read_only: true
      - "/etc/rtmp-hls-server/nginx.conf:/etc/nginx/nginx.conf"
      - "/etc/rtmp-hls-server/player:/etc/nginx/html/"
      - type: bind
        source: /etc/rtmp-hls-server/.htpasswd
        target: /.htpasswd
      - "/mnt/disks/data/:/mnt/"
      - "/etc/rtmp-hls-server/scripts:/scripts"


volumes:
  letsencrypt:
